---

all:
  vars:
    ansible_user: root

  children:
    community_cage:
      hosts:
        dev-01.kdlp.underground.software:
        prod-01.kdlp.underground.software:
        prod-02.kdlp.underground.software:

